# Organization managing order nodes

OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer1
        SANS:
          - 127.0.0.1
      - Hostname: orderer2
        SANS:
          - 127.0.0.1
      - Hostname: orderer3
        SANS:
          - 127.0.0.1

# Organization managing peer nodes
PeerOrgs:
  - Name: MedicFootprints
    Domain: medicfootprints.com
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - 127.0.0.1
    Users:
      Count: 1
