# Organization managing order nodes

OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3

# Organization managing peer nodes
PeerOrgs:
  - Name: MedicFootprints
    Domain: medicfootprints.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
